# Generated by Django 3.1.7 on 2021-03-21 13:34

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=30)),
                ('init_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_numb', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Lab_App.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('version', models.FloatField()),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Lab_App.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('body', models.TextField(max_length=500)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Lab_App.scientist')),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Lab_App.experiment')),
            ],
        ),
    ]
