# Generated by Django 3.1.7 on 2021-03-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0002_auto_20210328_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presentInExperiment', to='Lab_App.experiment'),
        ),
    ]
