# Generated by Django 3.1.7 on 2021-03-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0003_auto_20210328_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
