# Generated by Django 3.1.7 on 2021-03-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0004_auto_20210321_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
