# Generated by Django 3.1.7 on 2021-03-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_App', '0008_auto_20210321_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiments',
            new_name='Experiment',
        ),
    ]
